#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtk-img
Version  : 1.4.8+dfsg
Release  : 3
URL      : http://deb.debian.org/debian/pool/main/libt/libtk-img/libtk-img_1.4.8+dfsg.orig.tar.xz
Source0  : http://deb.debian.org/debian/pool/main/libt/libtk-img/libtk-img_1.4.8+dfsg.orig.tar.xz
Summary  : Loads and saves PNG files
Group    : Development/Tools
License  : BSL-1.0 GPL-2.0 Libpng TCL libtiff
Requires: libtk-img-lib = %{version}-%{release}
Requires: libtk-img-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
BuildRequires : fontconfig-dev
BuildRequires : freeglut-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXft-dev
BuildRequires : libpng-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(x11)
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : tk
BuildRequires : tk-dev
BuildRequires : tk-staticdev
BuildRequires : zlib-dev
Patch1: noman.patch

%description
Tcl/Tk Image formats (TkImg)
(Version 1.4.8 / December 2017)
Jan Nijtmans, Andreas Kupries, Paul Obermeier

%package dev
Summary: dev components for the libtk-img package.
Group: Development
Requires: libtk-img-lib = %{version}-%{release}
Provides: libtk-img-devel = %{version}-%{release}
Requires: libtk-img = %{version}-%{release}

%description dev
dev components for the libtk-img package.


%package lib
Summary: lib components for the libtk-img package.
Group: Libraries
Requires: libtk-img-license = %{version}-%{release}

%description lib
lib components for the libtk-img package.


%package license
Summary: license components for the libtk-img package.
Group: Default

%description license
license components for the libtk-img package.


%prep
%setup -q -n Img-1.4.8
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560752885
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1560752885
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libtk-img
cp compat/libpng/LICENSE %{buildroot}/usr/share/package-licenses/libtk-img/compat_libpng_LICENSE
cp compat/libpng/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_COPYING
cp compat/libpng/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_LICENSE
cp compat/libtiff/COPYRIGHT %{buildroot}/usr/share/package-licenses/libtk-img/compat_libtiff_COPYRIGHT
cp compat/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/libtk-img/compat_zlib_contrib_dotzlib_LICENSE_1_0.txt
cp license.terms %{buildroot}/usr/share/package-licenses/libtk-img/license.terms
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/Img1.4.8/pkgIndex.tcl
/usr/lib64/jpegtclConfig.sh
/usr/lib64/pngtclConfig.sh
/usr/lib64/tifftclConfig.sh
/usr/lib64/tkimgConfig.sh
/usr/lib64/zlibtclConfig.sh

%files dev
%defattr(-,root,root,-)
/usr/include/*.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/Img1.4.8/libjpegtcl9.2.so
/usr/lib64/Img1.4.8/libpngtcl1.6.35.so
/usr/lib64/Img1.4.8/libtifftcl3.9.7.so
/usr/lib64/Img1.4.8/libtkimg1.4.8.so
/usr/lib64/Img1.4.8/libtkimgbmp1.4.8.so
/usr/lib64/Img1.4.8/libtkimgdted1.4.8.so
/usr/lib64/Img1.4.8/libtkimggif1.4.8.so
/usr/lib64/Img1.4.8/libtkimgico1.4.8.so
/usr/lib64/Img1.4.8/libtkimgjpeg1.4.8.so
/usr/lib64/Img1.4.8/libtkimgpcx1.4.8.so
/usr/lib64/Img1.4.8/libtkimgpixmap1.4.8.so
/usr/lib64/Img1.4.8/libtkimgpng1.4.8.so
/usr/lib64/Img1.4.8/libtkimgppm1.4.8.so
/usr/lib64/Img1.4.8/libtkimgps1.4.8.so
/usr/lib64/Img1.4.8/libtkimgraw1.4.8.so
/usr/lib64/Img1.4.8/libtkimgsgi1.4.8.so
/usr/lib64/Img1.4.8/libtkimgsun1.4.8.so
/usr/lib64/Img1.4.8/libtkimgtga1.4.8.so
/usr/lib64/Img1.4.8/libtkimgtiff1.4.8.so
/usr/lib64/Img1.4.8/libtkimgwindow1.4.8.so
/usr/lib64/Img1.4.8/libtkimgxbm1.4.8.so
/usr/lib64/Img1.4.8/libtkimgxpm1.4.8.so
/usr/lib64/Img1.4.8/libzlibtcl1.2.11.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libtk-img/compat_libpng_LICENSE
/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_COPYING
/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_LICENSE
/usr/share/package-licenses/libtk-img/compat_libtiff_COPYRIGHT
/usr/share/package-licenses/libtk-img/compat_zlib_contrib_dotzlib_LICENSE_1_0.txt
/usr/share/package-licenses/libtk-img/license.terms
