#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtk-img
Version  : 1.4.7+dfsg
Release  : 2
URL      : http://deb.debian.org/debian/pool/main/libt/libtk-img/libtk-img_1.4.7+dfsg.orig.tar.xz
Source0  : http://deb.debian.org/debian/pool/main/libt/libtk-img/libtk-img_1.4.7+dfsg.orig.tar.xz
Summary  : zlib compression library
Group    : Development/Tools
License  : BSL-1.0 GPL-2.0 Libpng TCL libtiff
Requires: libtk-img-lib = %{version}-%{release}
Requires: libtk-img-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
BuildRequires : freeglut-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXft-dev
BuildRequires : libpng-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : tk
BuildRequires : tk-dev
BuildRequires : zlib-dev
Patch1: noman.patch

%description
Tcl/Tk Image formats (TkImg)
(Version 1.4.7 / December 2017)
Jan Nijtmans, Andreas Kupries, Paul Obermeier

%package dev
Summary: dev components for the libtk-img package.
Group: Development
Requires: libtk-img-lib = %{version}-%{release}
Provides: libtk-img-devel = %{version}-%{release}

%description dev
dev components for the libtk-img package.


%package lib
Summary: lib components for the libtk-img package.
Group: Libraries
Requires: libtk-img-license = %{version}-%{release}

%description lib
lib components for the libtk-img package.


%package license
Summary: license components for the libtk-img package.
Group: Default

%description license
license components for the libtk-img package.


%prep
%setup -q -n Img-Source-1.4.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543221449
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1543221449
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libtk-img
cp compat/libpng/LICENSE %{buildroot}/usr/share/package-licenses/libtk-img/compat_libpng_LICENSE
cp compat/libpng/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_COPYING
cp compat/libpng/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_LICENSE
cp compat/libtiff/COPYRIGHT %{buildroot}/usr/share/package-licenses/libtk-img/compat_libtiff_COPYRIGHT
cp compat/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/libtk-img/compat_zlib_contrib_dotzlib_LICENSE_1_0.txt
cp license.terms %{buildroot}/usr/share/package-licenses/libtk-img/license.terms
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/Img1.4.7/pkgIndex.tcl
/usr/lib64/jpegtclConfig.sh
/usr/lib64/pngtclConfig.sh
/usr/lib64/tifftclConfig.sh
/usr/lib64/tkimgConfig.sh
/usr/lib64/zlibtclConfig.sh

%files dev
%defattr(-,root,root,-)
/usr/include/*.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/Img1.4.7/libjpegtcl9.2.so
/usr/lib64/Img1.4.7/libpngtcl1.6.28.so
/usr/lib64/Img1.4.7/libtifftcl3.9.7.so
/usr/lib64/Img1.4.7/libtkimg1.4.7.so
/usr/lib64/Img1.4.7/libtkimgbmp1.4.7.so
/usr/lib64/Img1.4.7/libtkimgdted1.4.7.so
/usr/lib64/Img1.4.7/libtkimggif1.4.7.so
/usr/lib64/Img1.4.7/libtkimgico1.4.7.so
/usr/lib64/Img1.4.7/libtkimgjpeg1.4.7.so
/usr/lib64/Img1.4.7/libtkimgpcx1.4.7.so
/usr/lib64/Img1.4.7/libtkimgpixmap1.4.7.so
/usr/lib64/Img1.4.7/libtkimgpng1.4.7.so
/usr/lib64/Img1.4.7/libtkimgppm1.4.7.so
/usr/lib64/Img1.4.7/libtkimgps1.4.7.so
/usr/lib64/Img1.4.7/libtkimgraw1.4.7.so
/usr/lib64/Img1.4.7/libtkimgsgi1.4.7.so
/usr/lib64/Img1.4.7/libtkimgsun1.4.7.so
/usr/lib64/Img1.4.7/libtkimgtga1.4.7.so
/usr/lib64/Img1.4.7/libtkimgtiff1.4.7.so
/usr/lib64/Img1.4.7/libtkimgwindow1.4.7.so
/usr/lib64/Img1.4.7/libtkimgxbm1.4.7.so
/usr/lib64/Img1.4.7/libtkimgxpm1.4.7.so
/usr/lib64/Img1.4.7/libzlibtcl1.2.11.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libtk-img/compat_libpng_LICENSE
/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_COPYING
/usr/share/package-licenses/libtk-img/compat_libpng_contrib_gregbook_LICENSE
/usr/share/package-licenses/libtk-img/compat_libtiff_COPYRIGHT
/usr/share/package-licenses/libtk-img/compat_zlib_contrib_dotzlib_LICENSE_1_0.txt
/usr/share/package-licenses/libtk-img/license.terms
